FROM tensorflow/tensorflow:latest-gpu

RUN curl -sL https://deb.nodesource.com/setup_14.x | bash - \
    && apt-get update && apt-get install -y --no-install-recommends \
    git \
    nodejs \
    graphviz
